
#Refer to the /home/bob/playbooks/inventory file. We would like to run the /home/bob/playbooks/playbook.yaml on all servers defined under web_nodes group.

---
- name: 'Execute two commands on web_node1'
  hosts: web_nodes
  tasks:
     - name: 'Execute a date command'
       command: date
     - name: 'Execute a command to display hosts file'
       command: 'cat /etc/hosts'
